spring:
  application:
    name: location-service
  output:
    ansi:
      enabled: ALWAYS
  kafka:
    bootstrap-servers: http://localhost:9092

server:
  port: 9001

application:
  cars:
    total: 100